name: RareProperties
version: 1.1
main: wbe.rareproperties.RareProperties
api-version: 1.21
author: wbe
commands:
  RareProperties:
    description: RareProperties main command
    aliases: [rp]
    permission: rareproperties.command
